- src/components/DatePicker.vue
> Localise months

- README.md
- src/App.vue
- src/components/DatePicker.vue
- src/components/Day.vue
Added new option to allow a custom tooltipMessage to be applied. Also updated example page and the README. For #9
> Add custom tooltip

- README.md
- src/App.vue
- src/components/DatePicker.vue
https://github.com/krystalcampioni/vue-hotel-datepicker/issues/7
> added boolean option for single date selection

- .gitignore
- package-lock.json
- package.json
- src/App.vue
- src/components/DatePicker.vue
- src/components/helpers.js
- yarn.lock
Fix missing i18n when using Fecha library to format dates (checkin and checkout inputs). Add i18n with custom date format example (App.vue).
> Fix bug described in #75.

- README.md
- package.json
- src/components/DatePicker.vue
Display clear button only when dates are set, include displayClearButton prop`
> Clear button improvements

- src/components/DatePicker.vue
- src/components/helpers.js
when the check in date is greater than the start date, datepicker wrong months,
it fixed
> Active Month Fixes

- src/components/DatePicker.vue
Thank you for this beautiful gem!
> Fix typo in appearance css prop

- package-lock.json
- src/App.vue
- src/components/DatePicker.vue
if select forward date, when open the datepicker isnt show selected months in mobile
> Mobile Active Month Fixed

- src/App.vue
- src/components/DatePicker.vue
I don't know what exactly vuejs work, but this example is work on my project,
i hope it will helping someone who search how to use this function
> add example for using event check-in-changed and check-out-changed

- src/App.vue
- src/components/Day.vue
#201  UX improvements related to check-in selection.
> Feature/re-selection previous date #201

- src/components/DatePicker/index.vue
- src/components/Day.vue
@matiasperrone 
#211, modification for v4
> Change start date selection when selecting previous date (v4)

- src/DatePicker/HotelDatePicker.vue
> emit next month rendered

- src/i18n/it.js
Just added translation for italian
> Added it language

- src/DatePicker/HotelDatePicker.vue
Seems there were two redundant day object calls - maybe from the Day.vue component.  Removing these lines fixes the error.
> Describes the issue https://github.com/krystalcampioni/vue-hotel-datepicker/issues/269

- src/DatePicker/HotelDatePicker.vue
- src/assets/images/close.svg
> fixed close.svg and placed it inline to prevent asset issue

- src/DatePicker/HotelDatePicker.vue
- src/DatePicker/components/Day.vue
Hi, this is to fix the maxNight setting not working on v4.4.3
> #296 fixes max nights not showing

- src/DatePicker/HotelDatePicker.vue
> Call correct function on date formatting

- src/App.vue
- src/DatePicker/HotelDatePicker.vue
- src/DatePicker/components/Month.vue
- src/assets/scss/index.scss
- src/helpers.js
Feature to show week numbers. Highly requested by Scandinavian countries. Fix #81
> Added functionality to show weeknumbers

- README.md
- package.json
- src/App.vue
- src/DatePicker/HotelDatePicker.vue
- src/DatePicker/components/Month.vue
- src/assets/scss/index.scss
- src/helpers.js
Feature to show week numbers. Highly requested by Scandinavian countries. Fix https://github.com/ZestfulNation/vue-hotel-datepicker/issues/81
> [feature] Show week numbers

- src/DatePicker/HotelDatePicker.vue
Better for Accessibility = Higher SEO score
> Update Next/Prev month buttons to include aria labels
